campaigns/urls.py
"""URLs da aplicação campaigns."""

from django.conf import urls

from . import views

urlpatterns = [
    urls.url(r'^show/$', views.show_campaign, name='show_campaign'),
    urls.url(r'^$', views.list_campaigns, name='list_campaigns'),
    urls.url(r'^(?P<pk>\d+)/$', views.campaign_detail, name='campaign_detail'),
    urls.url(r'^(?P<pk>\d+)/activate/$', views.activate_campaign, name='activate_campaign'),
    urls.url(r'^(?P<pk>\d+)/cancel/$', views.cancel_campaign, name='cancel_campaign'),
    urls.url(r'^(?P<pk>\d+)/viewers/log/$', views.campaign_viewers, name='campaign_viewers'),
    urls.url(r'^(?P<pk>\d+)/chart/data/$', views.campaign_viewers_chart, name='campaign_viewers_chart'),
    # urls.url(r'^view/campaign/$', views.view_campaign, name='view_campaign'),
    urls.url(r'^view/campaign/redirect/$', views.view_campaign_redirect, name='view_campaign_redirect'),
    urls.url(r'^list/campaigns/template/$', views.list_campaigns_template, name='list_campaigns_template'),
    urls.url(r'^new/campaign/template/$', views.new_campaign_template, name='new_campaign_template'),
    urls.url(r'^campaign/detail/template/$', views.campaign_detail_template, name='campaign_detail_template'),
]

clickmob/urls.py
"""Módulo de configuração de urls do projeto."""

import os

from django.conf import settings, urls
from django.conf.urls import static
from django.contrib import admin
from django.contrib.auth.views import password_reset_complete, password_reset_confirm
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view
from tickets import views as tickets_views

from . import views

router = routers.DefaultRouter()
router.register('tickets', tickets_views.AdminTicketView)

urlpatterns = [
    urls.url(r'^$', views.IndexView.as_view(), name='home'),
    urls.url(r'^rest_auth/', urls.include('rest_auth.urls')),
    urls.url(r'^rest_auth/registration/', urls.include('rest_auth.registration.urls')),
    urls.url(r'^contas/', urls.include('allauth.urls')),
    urls.url(r'^api/v1/', urls.include(router.urls, namespace='v1')),
    urls.url(r'^api-auth/', urls.include('rest_framework.urls', namespace='rest_framework')),
    urls.url(r'^core/', urls.include('core.urls', namespace='core')),
    urls.url(r'^tickets/', urls.include('tickets.urls', namespace='tickets')),
    urls.url(r'^packs/', urls.include('packs.urls', namespace='packs')),
    urls.url(r'^campaigns/', urls.include('campaigns.urls', namespace='campaigns')),
    urls.url(r'^orders/', urls.include('orders.urls', namespace='orders')),
    urls.url(r'^mibank/', urls.include('mibank.urls', namespace='mibank')),
    urls.url(r'^admin/', urls.include(admin.site.urls)),
]

# auth urls utilizadas pelo rest_auth
urlpatterns += [
    urls.url(r'^contas/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
             password_reset_confirm, name='password_reset_confirm'),
    urls.url(r'^contas/reset/done/$', password_reset_complete, name='password_reset_complete'),
]

# media files in development
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_settings_module = os.environ.get('DJANGO_SETTINGS_MODULE')
if settings.DEBUG or 'heroku' in _settings_module or 'amazon_staging' in _settings_module:
    import debug_toolbar
    urlpatterns += [
        urls.url(r'^__debug__/', urls.include(debug_toolbar.urls)),
        urls.url(r'^schema/$', get_swagger_view(title='SlideCoins API')),
    ]

core/urls.py
"""Core urls."""

from django.conf import urls

from . import views

urlpatterns = [
    urls.url(r'^friends/$', views.friends, name='friends'),
    urls.url(r'^profile/$', views.profile, name='profile'),
    urls.url(r'^users/$', views.user_list, name='user_list'),
    urls.url(r'^users/detail/$', views.user_detail, name='user_detail'),
    urls.url(r'^navbar/template/$', views.user_info_template, name='user_info_template'),
    urls.url(r'^settings/template/$', views.settings_template, name='settings_template'),
]

campaigns/models.py
"""Modelos da aplicação campaigns."""

from core.models import gender_choices
from django import dispatch
from django.conf import settings
from django.contrib.gis.db import models
from django.contrib.postgres import fields
from django.db.models import signals
from django.utils import timezone
from model_utils.models import TimeStampedModel
from rest_framework import exceptions

from . import managers


def user_campaigns_images(instance, filename):
    """Define o diretório onde as imagens de uma campanha do usuário serão salvas."""
    return 'clickmob/campaigns/{}/{}/{}'.format(
        instance.owner.username,
        instance.title,
        filename
    )


class Campaign(TimeStampedModel, models.Model):
    """Uma campanha (ads) criada pelo usuário."""

    status_choices = [('Em Avaliação', 'Em Avaliação'), ('Ativa', 'Ativa'), ('Finalizada', 'Finalizada')]

    title = models.CharField(verbose_name='Título', max_length=50, unique=True)
    url = models.URLField()
    photo = models.ImageField(upload_to=user_campaigns_images)
    initial_n_views = models.PositiveIntegerField()
    n_views = models.PositiveIntegerField()
    status = models.CharField(max_length=20, choices=status_choices, default='Em Avaliação')
    is_active = models.BooleanField(default=False)
    is_canceled = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='campaigns')
    viewers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name='campaigns_viewed',
                                     through='UserCampaignViewLog')

    states = fields.ArrayField(models.CharField(max_length=2), blank=True, default=[])
    cities = fields.ArrayField(models.CharField(max_length=30), blank=True, default=[])
    countries = fields.ArrayField(models.CharField(max_length=30), blank=True, default=['Brasil'])
    center = models.PointField(srid=4326, null=True, blank=True)
    radius = models.FloatField(null=True, blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    gender = models.CharField(max_length=2, choices=gender_choices, blank=True)
    age = models.PositiveIntegerField(default=0)

    objects = managers.GeoCampaignManager()

    def is_valid_campaign(self):
        """Verifica se a campanha é válida em função de seus atributos."""
        now = timezone.now()
        return (self.is_active and not self.is_canceled and self.n_views >= 1 and self.start_date <= now and
                self.end_date >= now)

    def cancel_campaign(self):
        """Cancela, ou reativa a campanha, e atualiza as visualizações do usuário de acordo."""
        if self.n_views == 0:
            raise exceptions.ValidationError({
                'n_views': 'Uma campanha finalizada não pode ser cancelada.'
            })

        self.is_canceled = not self.is_canceled

        user = self.owner
        if self.is_canceled:
            user.n_views += self.n_views

        else:
            if (user.n_views - self.n_views) < 0:
                msg = 'Você não possui visualizações suficientes para reativar essa campanha. ' \
                      'Considere adquirir algum de nossos packs. Obrigado.'
                raise exceptions.ValidationError({
                    'n_views': msg
                })

            user.n_views -= self.n_views

        self.save()
        user.save()

    def save(self, *args, **kwargs):
        """Atualiza o número de views campanha para seu valor inicial."""
        if self.pk is None:
            self.n_views = self.initial_n_views

        return super().save(*args, **kwargs)

    def __str__(self):
        """toString."""
        return self.title

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Campanha'


class UserCampaignViewLog(models.Model):
    """Registra a visualização da campanha por um usuário."""

    interaction_type_choices = [('Visualização', 'Visualização'), ('Interação', 'Interação')]

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    campaign = models.ForeignKey(Campaign)
    view_date = models.DateTimeField(default=timezone.now)
    interaction_type = models.CharField(max_length=20, default='clique', choices=interaction_type_choices)

    objects = managers.UserCampaignViewManager()

    def __str__(self):
        """toString."""
        return '[Usuário={}][Campanha={}][Data={}]'.format(self.user.username,
                                                           self.campaign.title,
                                                           self.view_date)

    class Meta:
        ordering = ('-view_date',)


@dispatch.receiver(signals.post_save, sender=Campaign)
def update_owner_n_views_decrease(sender, instance, **kwargs):
    """Atualiza o número de views que o usuário possui após criar a campanha."""
    if kwargs.get('created', False):
        instance.owner.n_views -= instance.n_views
        instance.owner.save()

clickmob/views.py
"""Módulo contém views genéricas ou globais ao projeto."""

from core import serializers
from django.contrib.auth import mixins
from django.views import generic
from django.conf import settings
from rest_framework import renderers


class IndexView(mixins.LoginRequiredMixin, generic.TemplateView):
    """
    Página base da aplicação.

    Esta página contém a infraestrutura SPA (Single Page Application): scripts, estilos, etc.
    """

    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        """Redefine o contexto da página."""
        context = super().get_context_data(**kwargs)
        user_data = serializers.UserSerializer(self.request.user).data
        if user_data['total_items'] is None:
            user_data['total_items'] = 0

        context['User'] = renderers.JSONRenderer().render(user_data)
        context['GMAPS_KEY'] = settings.GMAPS_KEY
        return context

clickmob/templates/campaigns/campaign_detail_template.html
<div class="row" cg-busy="vm.promise">
  <div class="col-lg-12">
    <div class="box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">
          <i class="fa fa-bar-chart"></i> Analítico
        </h3>
        <div class="pull-right">
          <i class="fa fa-refresh pointer" style="font-size: 20px" ng-click="$state.go('campaigns.detail', {campaign: vm.campaign.id}, {reload: true})"></i>
        </div>
      </div>
      <div class="box-body table-responsive">
        <div class="row">
          <div class="col-lg-4">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">[[ vm.campaign.title ]]</h3>
              </div>

              <div class="panel-body">
                <p>Criada em: <span class="label label-info">[[ vm.campaign.created | date: "dd/MM/yyyy 'às' HH:mm:ss" ]]</span></p>
                <p>Número de Visualizações Inicial: <span class="label label-info">[[ vm.campaign.initial_n_views ]]</span></p>
                <p>Número de Visualizações Atual: <span class="label label-info">[[ vm.campaign.n_views ]]</span></p>
                <p>Está Ativa? <span class="label" ng-class="vm.campaign.is_active ? 'label-success' : 'label-danger'">[[ vm.campaign.is_active ? 'Sim' : 'Não' ]]</span></p>
                <p>Está Cancelada? <span class="label" ng-class="vm.campaign.is_canceled ? 'label-danger' : 'label-success'">[[ vm.campaign.is_canceled ? 'Sim' : 'Não' ]]</span></p>
                <p>Data de Início: <span class="label label-info">[[ vm.campaign.start_date | date: "dd/MM/yyyy 'às' HH:mm:ss" ]]</span></p>
                <p>Data de Término: <span class="label label-info">[[ vm.campaign.end_date | date: "dd/MM/yyyy 'às' HH:mm:ss" ]]</span></p>
                <p>Idade Minima para Visualizar a Campanha: <span class="label label-info">[[ vm.campaign.age ]]</span></p>
                <p>Campanha Destinada ao gênero: <span class="label label-info">[[ vm.campaign.gender === '' ? 'Todos' : vm.campaign.gender ]]</span></p>
                <div ng-show="vm.campaign.states.length > 0">
                  <p>Estados: <span style="margin-right: 5px" class="label label-info" ng-repeat="state in vm.campaign.states">[[ state ]]</span></p>
                </div>

                <div ng-show="vm.campaign.cities.length > 0">
                  <p>Cidades: <span style="margin-right: 5px" class="label label-info" ng-repeat="city in vm.campaign.cities">[[ city ]]</span></p>
                </div>

                <div ng-if="vm.campaign.radius && vm.campaign.center" style="width: 100%;">
                  <ui-gmap-google-map center='vm.campaignMap.center' zoom='vm.campaignMap.zoom' class="small-map">
                    <ui-gmap-marker coords="vm.campaignCenter.position" options="vm.campaignCenter.options"
                        idkey="vm.campaignCenter.id"></ui-gmap-marker>

                    <ui-gmap-circle center="vm.campaignCenter.position" stroke="vm.circle.stroke"
                        fill="vm.circle.fill"
                        radius="vm.circle.radius"></ui-gmap-circle>
                  </ui-gmap-google-map>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-8">
            <div class="panel panel-success" cg-busy="vm.chartPromise">
              <div class="panel-heading">
                <div class="row">
                  <h3 class="panel-title col-lg-6" style="margin-bottom: 10px">Visualizações da Campanha</h3>

                  <div class="col-lg-6">
                    <span>Tipo de Interação</span>
                    <select ng-model="vm.interaction_type_chart"
                        ng-change="vm.loadChartData({id: vm.campaign.id, type: vm.interaction_type_chart})"
                        style="margin-right: 10px">
                      <option value="">Todas</option>
                      <option value="Visualização">Visualização</option>
                      <option value="Interação">Interação</option>
                    </select>
                    <i class="fa fa-refresh pointer" style="font-size: 17px;"
                        ng-click="vm.loadChartData({id: vm.campaign.id, type: vm.interaction_type_chart})"></i>
                  </div>
                </div>
              </div>

              <div class="panel-body" style="padding: 10px 10px 30px 10px">
                <linechart data="vm.data" options="vm.options"></linechart>
              </div>

              <div class="panel-footer">
                <span>Total de Registros: [[ vm.chartCount ]]</span>
              </div>
            </div>

            <div class="panel panel-info" cg-busy="vm.viewersLogPromise">
              <div class="panel-heading">
                <div class="panel-title">
                  <div class="clearfix" style="margin-bottom: 10px">
                    <div class="pull-left">
                      <h4>Tabela de Interação de Usuários</h4>
                      <h5>Total de registros: [[ vm.viewersLog.count ]]</h5>
                    </div>
                    <span class="pull-right" style="cursor: pointer;position: relative;top: 15px"
                        ng-click="vm.loadViewersLog({'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})"
                        title="Recarregar registro de visualizações"><i class="fa fa-refresh"></i>
                    </span>
                    <div class="pull-right" style="margin-left: 5px;margin-right: 15px;position: relative;top: 10px; margin-bottom: 10px">
                      <span>Total por página:</span>
                      <select ng-options="value for value in [5, 10, 15, 20, 30]" ng-model="vm.page_size"
                          ng-change="vm.loadViewersLog({'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})"></select>
                    </div>
                    <div class="pull-right col-lg-4 col-md-4 col-xs-12" style="position: relative;top: 5px">
                      <form class="input-group">
                        <input type="text" class="form-control" placeholder="Busca" ng-model="vm.query">
                        <span class="input-group-btn">
                          <button class="btn btn-default" ng-click="vm.loadViewersLog({'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})">
                            <i class="fa fa-search"></i>
                          </button>
                        </span>
                      </form>
                    </div>
                  </div>
                </div>
              </div>

              <table class="table table-bordered table-hover">
                <thead>
                  <th>Usuário</th>
                  <th>Horário da Interação</th>
                  <th class="clearfix">
                    <span style="position: relative; top: 8px;">Tipo de Interação</span>
                    <select ng-model="vm.interaction_type" class="pull-right" style="margin-top: 10px"
                        ng-change="vm.loadViewersLog({'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})">
                      <option value="">Todas</option>
                      <option value="Visualização">Visualização</option>
                      <option value="Interação">Interação</option>
                    </select>
                  </th>
                </thead>

                <tbody>
                  <tr ng-repeat="log in vm.viewersLog.results">
                    <td>[[ log.username ]]</td>
                    <td>[[ log.view_date | date: "dd/MM/yyyy 'às' HH:mm:ss" ]]</td>
                    <td>[[ log.interaction_type ]]</td>
                  </tr>
                </tbody>
              </table>

              <div class="panel-footer clearfix" style="padding: 0">
                <nav aria-label="Page navigation" class="pull-right" ng-show="vm.viewersLog.page_range.length > 1" style="margin: 0 15px">
                  <ul class="pagination pagination-sm">
                    <li ng-class="{'disabled': !vm.viewersLog.has_previous}">
                      <a ng-click="vm.viewersLog.previous_page_number && vm.loadViewersLog({'page': vm.viewersLog.previous_page_number, 'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})"
                          aria-label="Previous" ng-class="{'pointer': vm.viewersLog.has_previous}">
                        <span aria-hidden="true"><i class="fa fa-chevron-left"></i></span>
                      </a>
                    </li>
                    <li ng-repeat="num_page in vm.viewersLog.page_range" ng-class="{'active': num_page === vm.viewersLog.number}" class="pointer">
                      <a ng-click="vm.loadViewersLog({'page': num_page, 'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})">[[ num_page ]]</a>
                    </li>
                    <li ng-class="{'disabled': !vm.viewersLog.has_next}">
                      <a ng-click="vm.viewersLog.next_page_number && vm.loadViewersLog({'page': vm.viewersLog.next_page_number, 'page_size': vm.page_size, 'search': vm.query, 'interaction_type': vm.interaction_type})"
                          aria-label="Next" ng-class="{'pointer': vm.viewersLog.has_next}">
                        <span aria-hidden="true"><i class="fa fa-chevron-right"></i></span>
                      </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

clickmob/templates/campaigns/new_campaign_template.html
<div class="row" cg-busy="vm.promise" id="top_campaign">
  <form name="newCampaignForm" novalidate>
    <div class="col-lg-12">
      <n-views></n-views>
      <div class="box box-solid">
        <div class="box-header with-border">
          <h3 class="box-title"><i class="fa fa-rss"></i> Nova Campanha</h3>
        </div>

        <div class="box-body">
          <div class="row">
            <div class="col-lg-7">

              <div class="form-group" ng-class="{'has-error': vm.errors.title}">
                <label for="">Título da Campanha</label>
                <input type="text" class="form-control" name="title" ng-model="vm.campaign.title" autofocus required>
                <span class="help-block" ng-show="vm.errors.title">
                  [[ vm.errors.title[0] ]]
                </span>
              </div>

              <div class="form-group" ng-class="{'has-error': vm.errors.url}">
                <label for="">URL da Campanha (não esqueça do <code>http://</code> ou <code>https://</code>)</label>
                <input type="text" class="form-control" name="url" ng-model="vm.campaign.url" required>
                <span class="help-block" ng-show="vm.errors.url">
                  URL inválida
                </span>
              </div>

              <div class="form-group" ng-class="{'has-error': vm.errors.photo}">
                <label for="">Imagem da Campanha</label>
                <input id="id_photo" type="file" class="filestyle" name="photo" fileread="vm.campaign.photo_file" ng-required>
                <span class="help-block" ng-show="vm.errors.photo">
                  Por favor, selecione uma imagem válida.
                </span>
              </div>

              <div class="form-group" ng-class="{'has-error': vm.errors.initial_n_views}">
                <label for="">Número de Visualizações</label>
                <input id="id_n_views" type="number" class="form-control" name="initial_n_views" ng-model="vm.campaign.initial_n_views" required>
                <span class="help-block" ng-show="vm.errors.initial_n_views">
                  [[ vm.errors.initial_n_views[0] ]]
                </span>
              </div>
            </div>

            <div class="col-lg-5">
              <div class="alert alert-success alert-dismissible" ng-show="vm.showCampaignMessage">
                <button type="button" class="close" ng-click="vm.showCampaignMessage = !vm.showCampaignMessage">
                  <span aria-hidden="true">&times;</span>
                </button>
                <p style="font-size: 14px">Sua campanha foi criada com sucesso e será imediatamente avaliada pela nossa equipe para que seja liberada o quanto antes. Obrigado!</p >
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-7">
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group" ng-class="{'has-error': vm.errors.start_date}">
                    <label for="">Data Inicial da Campanha <span ng-show="vm.errors.start_date">[[ vm.errors.start_date[0] ]]</span></label>
                    <input type="text" class="form-control" value='[[ vm.campaign.start_date | date:"dd/MM/yyyy HH:mm:ss" ]]'  disabled />
                    <div class="clearfix" style="margin-top: 5px">
                      <div class="pull-left" uib-datepicker ng-model="vm.campaign.start_date_date"
                          ng-change="vm.updateStartDate()"></div>
                      <div class="pull-left" uib-timepicker ng-model="vm.campaign.start_date_time"
                          ng-change="vm.updateStartDate()" show-meridian="false"
                          style="margin-left: 20px;padding-top: 0"></div>
                    </div>
                  </div>
                </div>

                <div class="col-lg-6">
                  <div class="form-group" ng-class="{'has-error': vm.errors.end_date}">
                    <label for="">Data Final da Campanha <span ng-show="vm.errors.end_date">[[ vm.errors.end_date[0] ]]</span></label>
                    <input type="text" class="form-control" value='[[ vm.campaign.end_date | date:"dd/MM/yyyy HH:mm:ss" ]]'  disabled />
                    <div class="clearfix" style="margin-top: 5px">
                      <div class="pull-left" uib-datepicker ng-model="vm.campaign.end_date_date"
                          ng-change="vm.updateEndDate()"></div>
                      <div class="pull-left" uib-timepicker ng-model="vm.campaign.end_date_time"
                          ng-change="vm.updateEndDate()" show-meridian="false"
                          style="margin-left: 20px;padding-top: 0"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-7">
              <div class="form-group">
                <label for="">Campanha destinada ao gênero</label>
                <select class="form-control" name="gender" ng-model="vm.campaign.gender">
                  <option value="">Todos</option>
                  <option value="M">Masculino</option>
                  <option value="F">Feminino</option>
                  <option value="O">Outro</option>
                </select>
              </div>

              <div class="form-group" ng-class="{'has-error': vm.errors.age}">
                <label for="">Idade Mínima para Visualização da Campanha (deixe em branco ou selecione 0 para todas as idades)</label>
                <input type="number" class="form-control" ng-model="vm.campaign.age">
                <span class="help-block" ng-show="vm.errors.age">
                  [[ vm.errors.age[0] ]]
                </span>
              </div>

              <div class="form-group">
                <label for="">Abrangência da campanha</label>
                <select ng-model="vm.campaignType" class="form-control" ng-change="vm.changeCampaignType()"
                    required>
                  <option value="">Selecione uma opção de abrangência</option>
                  <option value="0">Estados</option>
                  <option value="1">Cidades</option>
                  <option value="2">Área no mapa</option>
                </select>
              </div>

              <div ng-if="vm.campaignType === '0'">
                <h5>Pressione e segure a tecla "Control (Ctrl)" no seu teclado para selecionar mais de um estado.</h5>
                <select ng-model="vm.campaign.states" class="form-control" style="min-height: 500px"
                    ng-options="k as v.nome for (k, v) in vm.statesMap" required multiple></select>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12">
              <div ng-if="vm.campaignType === '1'">
                <div class="row">
                  <div class="col-lg-4">
                    <h5>Primeiro selecione um estado.</h5>
                    <select ng-model="vm.stateCity" class="form-control"
                        ng-options="k as v.nome for (k, v) in vm.statesMap"
                        ng-change="vm.showCities()"></select>
                  </div>

                  <div class="col-lg-4">
                    <h5>Em seguida clique nas cidades que deseja selecionar</h5>
                    <select ng-model="vm.selectedCities" ng-options="city for city in vm.cities"
                        style="min-height: 500px" class="form-control"
                        ng-change="vm.addCities()" multiple></select>
                  </div>

                  <div class="col-lg-4">
                    <h5>Lista de cidades selecionadas (clique para remover)</h5>
                    <select ng-model="vm.selectedCitiesRemove" ng-options="city for city in vm.campaign.cities"
                        style="min-height: 500px" class="form-control"
                        ng-change="vm.removeCities()" multiple></select>
                  </div>
                </div>
              </div>

              <div ng-if="vm.campaignType === '2'">
                <h5>Arraste os marcadores para selecionar o centro e o raio de abrangência da campanha.</h5>
                <ui-gmap-google-map center='vm.campaignMap.center' zoom='vm.campaignMap.zoom'>
                  <ui-gmap-marker coords="vm.campaignCenter.position" options="vm.campaignCenter.options"
                      events="vm.campaignCenter.events" idkey="vm.campaignCenter.id"></ui-gmap-marker>

                  <ui-gmap-marker coords="vm.campaignLimit.position" options="vm.campaignLimit.options"
                      events="vm.campaignLimit.events" idkey="vm.campaignLimit.id"></ui-gmap-marker>

                  <ui-gmap-circle center="vm.campaignCenter.position" stroke="vm.circle.stroke"
                      fill="vm.circle.fill"
                      radius="vm.circle.radius"></ui-gmap-circle>
                </ui-gmap-google-map>
              </div>

              <hr>
              <button ng-click="vm.createCampaign(newCampaignForm)" class="btn btn-primary"
                  ng-disabled="newCampaignForm.$invalid || (vm.campaignType === '1' && vm.campaign.cities.length === 0)">
                <i class="fa fa-save"></i> Criar campanha
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<script>
  $(function () {
    $('#id_photo').filestyle({
      'iconName': 'glyphicon glyphicon-picture',
      'buttonText': 'Imagem da campanha'
    });
  });
</script>