clickmob/urls.py
"""Módulo de configuração de urls do projeto."""

import os

from django.conf import settings, urls
from django.conf.urls import static
from django.contrib import admin
from django.contrib.auth.views import password_reset_complete, password_reset_confirm
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view
from tickets import views as tickets_views

from . import views

router = routers.DefaultRouter()
router.register('tickets', tickets_views.AdminTicketView)

urlpatterns = [
    urls.url(r'^$', views.IndexView.as_view(), name='home'),
    urls.url(r'^rest_auth/', urls.include('rest_auth.urls')),
    urls.url(r'^rest_auth/registration/', urls.include('rest_auth.registration.urls')),
    urls.url(r'^contas/', urls.include('allauth.urls')),
    urls.url(r'^api/v1/', urls.include(router.urls, namespace='v1')),
    urls.url(r'^api-auth/', urls.include('rest_framework.urls', namespace='rest_framework')),
    urls.url(r'^core/', urls.include('core.urls', namespace='core')),
    urls.url(r'^tickets/', urls.include('tickets.urls', namespace='tickets')),
    urls.url(r'^packs/', urls.include('packs.urls', namespace='packs')),
    urls.url(r'^campaigns/', urls.include('campaigns.urls', namespace='campaigns')),
    urls.url(r'^orders/', urls.include('orders.urls', namespace='orders')),
    urls.url(r'^mibank/', urls.include('mibank.urls', namespace='mibank')),
    urls.url(r'^admin/', urls.include(admin.site.urls)),
]

# auth urls utilizadas pelo rest_auth
urlpatterns += [
    urls.url(r'^contas/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
             password_reset_confirm, name='password_reset_confirm'),
    urls.url(r'^contas/reset/done/$', password_reset_complete, name='password_reset_complete'),
]

# media files in development
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_settings_module = os.environ.get('DJANGO_SETTINGS_MODULE')
if settings.DEBUG or 'heroku' in _settings_module or 'amazon_staging' in _settings_module:
    import debug_toolbar
    urlpatterns += [
        urls.url(r'^__debug__/', urls.include(debug_toolbar.urls)),
        urls.url(r'^schema/$', get_swagger_view(title='SlideCoins API')),
    ]

core/urls.py
"""Core urls."""

from django.conf import urls

from . import views

urlpatterns = [
    urls.url(r'^friends/$', views.friends, name='friends'),
    urls.url(r'^profile/$', views.profile, name='profile'),
    urls.url(r'^users/$', views.user_list, name='user_list'),
    urls.url(r'^users/detail/$', views.user_detail, name='user_detail'),
    urls.url(r'^navbar/template/$', views.user_info_template, name='user_info_template'),
    urls.url(r'^settings/template/$', views.settings_template, name='settings_template'),
]

core/models.py
"""Modelos da aplicação core."""

import decimal
import shutil
from os import path

from django import dispatch
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import signals
from model_utils.models import TimeStampedModel

gender_choices = [('', ''), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')]


def user_image_folder(instance, filename):
    """Define o diretório para as imagens de usuário."""
    return 'clickmob/user_images/{0}/{1}'.format(instance.username, filename)


class User(TimeStampedModel, AbstractUser):
    """Usuário base do projeto."""

    user_image = models.ImageField(upload_to=user_image_folder, null=True, blank=True)
    phone = models.CharField(max_length=16, blank=True)
    country = models.CharField(max_length=15, default='Brasil')
    gender = models.CharField(max_length=2, choices=gender_choices, blank=True)

    friend = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name='friends', blank=True)
    user_type = models.PositiveIntegerField(default=0)
    user_points = models.PositiveIntegerField(default=0)
    network_points = models.PositiveIntegerField(default=0)
    n_views = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Usuário'
        ordering = ('-created',)


class BankBalance(models.Model):
    """Saldo do usuário no mês."""

    status_choices = [('Parcial', 'Parcial'), ('Integrado', 'Integrado'), ('Enviado', 'Enviado'),
                      ('Pago', 'Pago')]

    status = models.CharField(max_length=10, default='parcial', choices=status_choices)
    balance = models.DecimalField(decimal_places=2, max_digits=7, default=decimal.Decimal('0.00'))
    month = models.DateTimeField()
    limit_value = models.DecimalField(decimal_places=2, max_digits=7)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)


class Profile(models.Model):
    """A criação deste profile é necessária para permissão da compra de publicidade."""

    user = models.OneToOneField(User)
    sacado_uf = models.CharField(max_length=2)
    sacado_cidade = models.CharField(max_length=40)
    sacado_bairro = models.CharField(max_length=40)
    sacado_cep = models.CharField(max_length=10)
    sacado_numero = models.CharField(max_length=10)
    sacado_logradouro = models.CharField(max_length=255)
    sacado_documento = models.CharField(max_length=40)


@dispatch.receiver(signals.post_delete, sender=User)
def auto_delete_files_on_delete(sender, instance, **kwargs):
    """
    Remove o diretório contendo arquivos do usuário na deleção do mesmo.

    Atenção extrema em relação ao diretório a ser removido para evitar possíveis desastres.
    """
    if instance.user_image:
        shutil.rmtree(path.dirname(instance.user_image.path), ignore_errors=True)

core/forms.py
"""Formulários da aplicação core."""

from django import forms
from django.contrib import auth


class CoreSignupForm(forms.Form):
    """Formulário de registro contendo campos extras."""

    first_name = forms.CharField(required=True, max_length=32)
    user_image = forms.ImageField(required=False)
    phone = forms.CharField(required=False, max_length=16)
    friend = forms.ModelChoiceField(
        queryset=auth.get_user_model().objects.all(),
        empty_label='-- ID do amigo --',
        required=False,
        widget=forms.widgets.TextInput
    )
    is_affiliated = forms.BooleanField(required=False)

    def signup(self, request, user):
        """no op."""

clickmob/views.py
"""Módulo contém views genéricas ou globais ao projeto."""

from core import serializers
from django.contrib.auth import mixins
from django.views import generic
from django.conf import settings
from rest_framework import renderers


class IndexView(mixins.LoginRequiredMixin, generic.TemplateView):
    """
    Página base da aplicação.

    Esta página contém a infraestrutura SPA (Single Page Application): scripts, estilos, etc.
    """

    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        """Redefine o contexto da página."""
        context = super().get_context_data(**kwargs)
        user_data = serializers.UserSerializer(self.request.user).data
        if user_data['total_items'] is None:
            user_data['total_items'] = 0

        context['User'] = renderers.JSONRenderer().render(user_data)
        context['GMAPS_KEY'] = settings.GMAPS_KEY
        return context

core/views.py
"""Views da aplicação core."""

from core.pagination import CorePaginator
from django.contrib import auth
from django.views import generic
from rest_framework import filters, generics, permissions

from . import serializers


class UserListView(generics.ListAPIView):
    """Obtém a lista de usuários."""

    serializer_class = serializers.UserSerializer
    permission_classes = (permissions.IsAdminUser,)
    queryset = auth.get_user_model().objects.exclude(is_superuser=True)
    pagination_class = CorePaginator
    search_fields = ['username', 'email']


user_list = UserListView.as_view()


class UserDetailView(generics.RetrieveUpdateAPIView):
    """Obtém ou atualiza informações do usuário logado. Deve ser utilizada no lugar de /rest_auth/user/."""

    serializer_class = serializers.UserSerializer
    permission_classes = (permissions.IsAuthenticated,)
    queryset = auth.get_user_model().objects.all()

    def get_object(self):
        """Retorna o usuário logado."""
        return self.request.user


user_detail = UserDetailView.as_view()


class FriendView(generics.ListAPIView):
    """Obtém uma lista de usuários para serem utilizados como amigos no processo de registro."""

    serializer_class = serializers.FriendSerializer
    pagination_class = CorePaginator
    queryset = auth.get_user_model().objects.all()
    filter_backends = (filters.SearchFilter,)
    search_fields = ['username']

    def get_queryset(self):
        """Obtém o queryset. Nesse caso, admins não podem ser selecionados como amigo."""
        return super().get_queryset().exclude(is_superuser=True)


friends = FriendView.as_view()


class ProfileView(generics.CreateAPIView):
    """Cria o profile do usuário."""

    serializer_class = serializers.ProfileSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def perform_create(self, serializer):
        """Passa o usuário logado para o serializador."""
        serializer.save(user=self.request.user)


profile = ProfileView.as_view()


class UserInfoTemplateView(generic.TemplateView):
    """Obtém o template server side para o componente navbar."""

    template_name = 'core/user_info_template.html'


user_info_template = UserInfoTemplateView.as_view()


class SettingsTemplateView(generic.TemplateView):
    """Obtém o template server side para o componente navbar."""

    template_name = 'core/settings_template.html'


settings_template = SettingsTemplateView.as_view()

clickmob/templates/core/settings_template.html
<div class="row" cg-busy="vm.pagePromise">

  <div class="col-lg-4">
    <div class="box box-solid" cg-busy="vm.updateUserDataPromise">
      <div class="box-header with-border">
        <h3 class="box-title">Dados cadastrais</h3>
      </div>

      <div class="box-body">
        <form name="personalDataForm" enctype="multipart/form-data" novalidate>
          <div class="form-group">
            <label for="">Imagem do perfil</label>
            <input id="id_user_image" type="file" name="user_image" fileread="vm.User.user_image">
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.userDataErrors.first_name}">
            <label for="">Nome completo</label>
            <input type="text" class="form-control" name="first_name" ng-model="vm.User.first_name" />
            <span class="help-block" ng-show="vm.userDataErrors.first_name">
              [[ vm.userDataErrors.first_name[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback">
            <label for="">Telefone</label>
            <input type="text" class="form-control" name="phone" ng-model="vm.User.phone" ui-br-phone-number="" />
            <span class="glyphicon glyphicon-phone form-control-feedback"></span>
          </div>

          <div class="form-group has-feedback">
            <label for="">Gênero</label>
            <select class="form-control" name="gender" ng-model="vm.User.gender">
              <option value=""></option>
              <option value="M">Masculino</option>
              <option value="F">Feminino</option>
              <option value="O">Outro</option>
            </select>
          </div>

          <hr/>
          <button class="btn btn-default pull-right" ng-click="vm.updateUserData()">
            <i class="fa fa-refresh"></i> Atualizar dados cadastrais
          </button>
        </form>
      </div>
    </div>
  </div>

  <div class="col-lg-4" ng-if="User.user_type >= 1">
    <div class="box box-solid" cg-busy="vm.createProfilePromise">

      <div class="box-header with-border">
        <h3 class="box-title">Informações de Cobrança</h3>
      </div>

      <div class="box-body">
        <form name="profileForm" novalidate>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_documento}">
            <label for="">CPF/CNPJ</label>
            <input type="text" class="form-control" name="sacado_documento" ng-model="vm.User.profile.sacado_documento" ui-br-cpfcnpj-mask required/>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_documento">
              [[ vm.profileDataErrors.sacado_documento[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_uf}">
            <label for="">Estado</label>
            <select class="form-control" name="state"  ng-model="vm.User.profile.sacado_uf" ng-change="vm.setCities()" required>
              <option ng-repeat="state in vm.states" value="[[ state ]]">[[ state ]]</option>
            </select>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_uf">
              [[ vm.profileDataErrors.sacado_uf[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_cidade}">
            <label for="">Cidade</label>
            <select class="form-control" name="city" ng-model="vm.User.profile.sacado_cidade"> required
              <option ng-repeat="city in vm.cities" value="[[ city ]]">[[ city ]]</option>
            </select>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_cidade">
              [[ vm.profileDataErrors.sacado_cidade[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_bairro}">
            <label for="">Bairro</label>
            <input type="text" class="form-control" name="sacado_bairro" ng-model="vm.User.profile.sacado_bairro" required/>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_bairro">
              [[ vm.profileDataErrors.sacado_bairro[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_logradouro}">
            <label for="">Endereço</label>
            <input type="text" class="form-control" name="sacado_logradouro" ng-model="vm.User.profile.sacado_logradouro" required/>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_logradouro">
              [[ vm.profileDataErrors.sacado_logradouro[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_numero}">
            <label for="">Número</label>
            <input type="text" class="form-control" name="sacado_numero" ng-model="vm.User.profile.sacado_numero" required/>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_numero">
              [[ vm.profileDataErrors.sacado_numero[0] ]]
            </span>
          </div>

          <div class="form-group has-feedback" ng-class="{'has-error': vm.profileDataErrors.sacado_cep}">
            <label for="">CEP</label>
            <input type="text" class="form-control" name="sacado_cep" ng-model="vm.User.profile.sacado_cep" ui-br-cep-mask required/>
            <span class="help-block" ng-show="vm.profileDataErrors.sacado_cep">
              [[ vm.profileDataErrors.sacado_cep[0] ]]
            </span>
          </div>

          <hr/>
          <button class="btn btn-default pull-right" ng-click="vm.saveProfileData()" ng-disabled="profileForm.$invalid">
            <i class="fa fa-refresh"></i> Salvar informações de cobrança
          </button>
        </form>
      </div>

    </div>
  </div>

  <div class="col-lg-4">
    <div class="box box-solid" cg-busy="vm.changePasswordPromise">
      <div class="box-header with-border">
        <h3 class="box-title">Atualizar senha</h3>
      </div>

      <div class="box-body">
        <form name="passwordChangeForm" novalidate>
          <div class="form-group" ng-class="{'has-error': vm.changePasswordErrors.old_password}">
            <label for="">Senha antiga</label>
            <input type="password" class="form-control" name="old_password" ng-model="vm.changePasswordData.old_password" required/>
            <span class="help-block" ng-show="vm.changePasswordErrors.old_password">Senha inválida.</span>
          </div>
          <div class="form-group" ng-class="{'has-error': vm.changePasswordErrors.new_password1}">
            <label for="">Nova senha</label>
            <input type="password" class="form-control" name="new_password1" ng-model="vm.changePasswordData.new_password1" required/>
            <span class="help-block text-danger" ng-show="vm.changePasswordErrors.new_password1">
              [[ vm.changePasswordErrors.new_password1[0] ]]
            </span>
          </div>
          <div class="form-group" ng-class="{'has-error': vm.changePasswordErrors.new_password2}">
            <label for="">Confirmar nova senha</label>
            <input type="password" class="form-control" name="new_password2" ng-model="vm.changePasswordData.new_password2" required/>
            <span class="help-block text-danger" ng-show="vm.changePasswordErrors.new_password2">
              [[ vm.changePasswordErrors.new_password2[0] ]]
            </span>
          </div>
          <hr/>
          <button class="btn btn-default pull-right" ng-click="vm.changePassword()" ng-disabled="passwordChangeForm.$invalid">
            <i class="fa fa-refresh"></i> Atualizar senha
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  $('#id_user_image').filestyle({
    iconName: 'glyphicon glyphicon-picture',
    buttonText: 'Imagem do perfil'
  });
</script>

clickmob/templates/core/user_info_template.html
<li class="dropdown user user-menu">{% load user_image from core_tags %}
  <!-- Menu Toggle Button -->
  <a href="" class="dropdown-toggle" data-toggle="dropdown">
    <!-- The user image in the navbar-->
    <img ng-src="[[ User.user_image ]]" class="user-image" alt="User Image">
    <!-- hidden-xs hides the username on small devices so only the image appears. -->
    <span class="hidden-xs">[[ User.first_name ]]</span> <i class="fa fa-caret-down" style="margin-left: 5px"></i>
  </a>
  <ul class="dropdown-menu">
    <!-- The user image in the menu -->
    <li class="user-header">
      <img ng-src="[[ User.user_image ]]"  class="img-circle" alt="User Image">
      <p>
        [[ User.first_name ]]
        <small>Desde [[ User.created | date: "dd/MM/yyyy 'às' HH:mm:ss" ]]</small>
      </p>
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a class="btn btn-default btn-flat pointer" ui-sref="settings">
          <i class="fa fa-cogs"></i> Configurações
        </a>
      </div>
      <div class="pull-right">
        <a ng-click="vm.logout()" class="btn btn-default btn-flat">
          <i class="fa fa-sign-out"></i> Logout
        </a>
      </div>
    </li>
  </ul>
</li>